from app.mcp_server.executor import ToolSpec


TOOL_SPECS = {
    "create_order": ToolSpec(
        name="create_order",
        permissions=("manage_orders",),
    ),
    "resolve_entities": ToolSpec(
        name="resolve_entities",
        permissions=(),
        risk_level="entity_resolution",
    ),
    "list_recipe_component_options": ToolSpec(
        name="list_recipe_component_options",
        permissions=(),
        full_tier_required=True,
        risk_level="recipe_component_lookup",
    ),
    "update_order": ToolSpec(
        name="update_order",
        permissions=("manage_orders",),
        confirmation_required=True,
        risk_level="order_edit",
    ),
    "change_order_status": ToolSpec(
        name="change_order_status",
        permissions=("manage_orders",),
        confirmation_required=True,
        risk_level="order_status",
    ),
    "create_menu_item": ToolSpec(
        name="create_menu_item",
        permissions=("edit_menu",),
    ),
    "update_menu_item": ToolSpec(
        name="update_menu_item",
        permissions=("edit_menu",),
    ),
    "set_menu_item_active": ToolSpec(
        name="set_menu_item_active",
        permissions=("edit_menu",),
        confirmation_required=True,
        risk_level="menu_lifecycle",
    ),
    "create_recipe": ToolSpec(
        name="create_recipe",
        permissions=("add_recipe",),
        full_tier_required=True,
    ),
    "update_recipe": ToolSpec(
        name="update_recipe",
        permissions=("edit_recipe",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="recipe_component_replacement",
    ),
    "create_batch_recipe": ToolSpec(
        name="create_batch_recipe",
        permissions=("batch_create_recipe",),
        full_tier_required=True,
    ),
    "update_batch_recipe": ToolSpec(
        name="update_batch_recipe",
        permissions=("batch_edit_recipe",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="batch_component_replacement",
    ),
    "link_ingredient_supplier": ToolSpec(
        name="link_ingredient_supplier",
        permissions=("manage_suppliers",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="supplier_link",
    ),
    "update_ingredient_supplier": ToolSpec(
        name="update_ingredient_supplier",
        permissions=("manage_suppliers",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="supplier_link_update",
    ),
    "import_sales_entries": ToolSpec(
        name="import_sales_entries",
        permissions=("upload_sales",),
        confirmation_required=True,
        risk_level="sales_import",
    ),
    "adjust_inventory_quantity": ToolSpec(
        name="adjust_inventory_quantity",
        permissions=("adjust_inventory",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="inventory_correction",
    ),
    "set_inventory_current_stock": ToolSpec(
        name="set_inventory_current_stock",
        permissions=("adjust_inventory",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="inventory_reconciliation",
    ),
    "list_purchase_orders": ToolSpec(
        name="list_purchase_orders",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        risk_level="purchase_order_read",
    ),
    "get_purchase_order": ToolSpec(
        name="get_purchase_order",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        risk_level="purchase_order_read",
    ),
    "list_ingredient_suppliers": ToolSpec(
        name="list_ingredient_suppliers",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        risk_level="purchase_lookup",
    ),
    "list_inventory_stock_levels": ToolSpec(
        name="list_inventory_stock_levels",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        risk_level="purchase_lookup",
    ),
    "get_purchase_order_suggestions": ToolSpec(
        name="get_purchase_order_suggestions",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        risk_level="purchase_suggestion",
    ),
    "create_purchase_order": ToolSpec(
        name="create_purchase_order",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_create",
    ),
    "create_purchase_orders_from_suggestions": ToolSpec(
        name="create_purchase_orders_from_suggestions",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_suggestion_create",
    ),
    "add_purchase_order_item": ToolSpec(
        name="add_purchase_order_item",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_edit",
    ),
    "update_purchase_order_item": ToolSpec(
        name="update_purchase_order_item",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_edit",
    ),
    "remove_purchase_order_item": ToolSpec(
        name="remove_purchase_order_item",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_edit",
    ),
    "change_purchase_order_status": ToolSpec(
        name="change_purchase_order_status",
        permissions=("manage_purchase_orders",),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_status",
    ),
    "receive_purchase_order": ToolSpec(
        name="receive_purchase_order",
        permissions=("manage_purchase_orders", "adjust_inventory"),
        full_tier_required=True,
        confirmation_required=True,
        risk_level="purchase_order_receipt",
    ),
}
